name: Vineet Kumar
favicon: null
layout_spectrum: 0.9625907512381673
typography_spectrum: 0.5310190534219146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.33846646011807024
  lightness: 0.7399297019001096
  saturation: 0.8206224497407675
  rhythmicContrast: 0.353094017598778
purpose: []
